name: iso_build
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  prepare_release:
    runs-on: ubuntu-20.04
    steps:
      - 
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - 
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDDHHmm'
      - 
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.time.outputs.time }}
          release_name: Release ${{ steps.time.outputs.time }}
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
      release_id: ${{ steps.release.outputs.id }}

  release:
    runs-on: ubuntu-20.04
    needs: prepare_release    
    strategy:
      matrix:
        ##### EDIT ME #####      
        EDITION: [kde]
        BRANCH: [stable]
        SCOPE: [minimal]
        ###################
    steps:
      - 
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      -
        id: image-build
        uses: manjaro/manjaro-iso-action@main
        with:
          iso-profiles-repo: 'https://github.com/dotiful/iso-profiles'
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          scope: ${{ matrix.scope }}
          version: ${{ steps.time.outputs.time }}-dev
          kernel: linux510
          code-name: "Ornara"
          release-tag: ${{ needs.prepare-release.outputs.release_tag }}
      
      - 
        name: rollback github release
        if: ${{ failure() || cancelled() }}
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh release delete ${{ needs.prepare-release.outputs.release_tag }} -y --repo ${{ github.repository }}
          git push --delete origin ${{ needs.prepare-release.outputs.release_tag }}
