name: iso_build
on:
  workflow_dispatch:
  #schedule:
  #  - cron:  '30 2 * * *'

jobs:
  prepare_release:
    runs-on: ubuntu-20.04
    steps:
      - 
        name: Prepare Cancel Workflow
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - 
        name: Get current time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDDHHmm'
      - 
        name: Prepare Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.time.outputs.time }}
          release_name: Release ${{ steps.time.outputs.time }}
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
      release_id: ${{ steps.release.outputs.id }}

  release:
    runs-on: ubuntu-20.04
    needs: prepare_release    
    strategy:
      matrix:
        ###### EDIT HERE ######
        EDITION: [kde]
        BRANCH: [stable]
        SCOPE: [minimal]
        #######################
    steps:
      - 
        name: Prepare Cancel Workflow
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      
      # -
      #   name: Checkout ISO-Profiles
      #   run: |          
      #     sudo git clone https://gitlab.manjaro.org/profiles-and-settings/iso-profiles.git 
          
      - 
        name: Checkout ISO-Profiles
        uses: actions/checkout@v2
        with:
          ###### EDIT HERE ######
          repository: dotiful/iso-profiles
          #######################
          token: "${{ secrets.GITHUB_TOKEN }}"
          path: 'iso-profiles'

      - 
        name: Get current time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YY.MM'          

      -
        id: image-build
          uses: manjaro/manjaro-iso-action@main
          with:
            edition: ${{ matrix.edition }}
            branch: ${{ matrix.branch }}
            scope: ${{ matrix.scope }}
            version: ${{ steps.time.outputs.time }}-development
            kernel: linux510
            code-name: "Ornara"

      - 
        name: Upload Release
        id: upload_release_zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ steps.image-build.outputs.file-path }}.zip
          asset_name: ${{ steps.image-build.outputs.file-path }}.zip
          asset_content_type: application/zip
      - 
        name: Check for split-zip
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ${{ steps.image-build.outputs.file-path }}.z01
          allow_failure: false
      - 
        name: Upload Release (split-zip)
        id: upload_release_z01
        uses: actions/upload-release-asset@v1
        if: steps.check_files.outputs.files_exists == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ steps.image-build.outputs.file-path }}.z01
          asset_name: ${{ steps.image-build.outputs.file-path }}.z01
          asset_content_type: application/zip
      - 
        name: Upload Checksum file
        id: upload_sha256
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ steps.image-build.outputs.file-sha256 }}
          asset_name: ${{ steps.image-build.outputs.file-sha256 }}
          asset_content_type: text/plain
      - 
        name: Upload Package list
        id: upload_pkg
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ steps.image-build.outputs.file-pkg }}
          asset_name: ${{ steps.image-build.outputs.file-pkg }}
          asset_content_type: text/plain     
      - 
        name: Rollback Release
        if: failure()
        uses: author/action-rollback@stable
        with:
          release_id: ${{ needs.prepare_release.outputs.release_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
